/**
 * The options reference, rendered for docs/02 (P9-21).
 *
 * Generated rather than written, because a table of a hundred and forty rows that is typed by
 * hand is a table that is wrong somewhere within a month. `scripts/options-doc.ts` writes it
 * between two markers in docs/02-domain-model.md, and `tests/options.test.ts` fails when the
 * document no longer matches what this produces — so the doc, the dropdowns and the schema
 * cannot say three different things.
 *
 * Pure: a string from the tables, with no IO, so the test can call it.
 */
import { OPTION_TABLES } from './options'

// The prettier range markers are part of the block: the tables are generated in a fixed
// shape, and a formatter that re-pads them would leave the document one format run away from
// failing the test that checks it.
export const OPTIONS_DOC_START = [
  '<!-- options:start — generated by `pnpm --filter @agent-blueprint/core options:doc`; do not edit by hand -->',
  '<!-- prettier-ignore-start -->',
].join('\n')
export const OPTIONS_DOC_END = ['<!-- prettier-ignore-end -->', '<!-- options:end -->'].join('\n')

/** Which schema field each table is the options of, for the heading. */
const HEADINGS: Record<keyof typeof OPTION_TABLES, string> = {
  AGENT_ROLES: 'Agent `role`',
  SEVERITIES: 'Severity (`severity` on hooks, findings and AI checks)',
  IRON_LAW_SEVERITIES: 'Iron Law `severity`',
  GOVERNANCE_CATEGORIES: 'Iron Law and rule `category`',
  TOOL_KINDS: 'Tool `kind`',
  PERMISSION_OPERATIONS: 'Permission operations (`permissions.operations`)',
  PERMISSION_DECISIONS: 'Permission decisions',
  MODEL_PREFERENCES: 'Agent `model.preference`',
  ENFORCEMENT_MECHANISMS: 'Iron Law `enforcement`',
  RULE_PRIORITIES: 'Rule `priority`',
  HOOK_TRIGGERS: 'Hook `trigger`',
  HOOK_ACTION_TYPES: 'Hook `action.type`',
  HOOK_FAILURE_BEHAVIORS: 'Hook `onFailure`',
  GATE_CRITERION_KINDS: 'Gate `criteria[].kind`',
  GATE_FAILURE_BEHAVIORS: 'Gate `onFail`',
  MCP_TRANSPORTS: 'Tool `mcp.transport`',
  REFERENCE_KINDS: 'Reference `kind`',
  MEMORY_SCOPES: 'Memory `scope`',
  REQUIREMENT_CHECK_TYPES: 'Requirement `checks[].type`',
  REQUIREMENT_LEVELS: 'Requirement `level`',
  SCENARIO_MODES: 'Scenario `mode`',
  SKILL_RESOURCE_KINDS: 'Skill `resources[].kind`',
  SKILL_RESOURCE_ENCODINGS: 'Skill `resources[].encoding`',
  WORKFLOW_NODE_TYPES: 'Workflow step `type`',
  WORKFLOW_EDGE_KINDS: 'Workflow connection `kind`',
  MERGE_STRATEGIES: 'Workflow step `config.mergeStrategy`',
  VERIFICATION_METHODS: 'Workflow step `config.verification.method`',
  NODE_FAILURE_BEHAVIORS: 'Workflow step `config.onFailure`',
  HARNESS_IDS: 'Compile target `harnessId`',
}

/** Pipes inside a cell would end it; the descriptions do not use them, but the test does not care. */
function cell(text: string): string {
  return text.replace(/\|/g, '\\|')
}

export function renderOptionsDoc(): string {
  const lines: string[] = [
    OPTIONS_DOC_START,
    '',
    'Every fixed choice a form offers, with what choosing it does. The same text is shown beside each option in the app; both come from `packages/core/src/model/options.ts`.',
  ]
  for (const name of Object.keys(OPTION_TABLES) as (keyof typeof OPTION_TABLES)[]) {
    const [values, info] = OPTION_TABLES[name]
    lines.push('', `#### ${HEADINGS[name]}`, '', '| Value | Label | Means |', '| --- | --- | --- |')
    for (const value of values) {
      const entry = (info as Readonly<Record<string, { label: string; description: string }>>)[
        value
      ]
      if (!entry) continue
      lines.push(`| \`${value}\` | ${cell(entry.label)} | ${cell(entry.description)} |`)
    }
  }
  lines.push('', OPTIONS_DOC_END)
  return lines.join('\n')
}

/** The document with the generated section replaced, or appended when the markers are absent. */
export function withOptionsDoc(document: string): string {
  const rendered = renderOptionsDoc()
  const start = document.indexOf(OPTIONS_DOC_START)
  const end = document.indexOf(OPTIONS_DOC_END)
  if (start >= 0 && end > start) {
    return document.slice(0, start) + rendered + document.slice(end + OPTIONS_DOC_END.length)
  }
  return `${document.trimEnd()}\n\n## Options reference\n\n${rendered}\n`
}
