/**
 * Every generated Markdown file says where it came from, so a developer who opens the
 * repository in an editor knows not to edit it.
 *
 * The comment goes on the first line of plain Markdown files, and on the first line of the
 * *body* of files with YAML frontmatter: frontmatter must start at byte 0 or the harness
 * will not parse it. JSON, TOML and YAML outputs carry no header (JSON has no comments, and
 * a comment in a config file tends to leak into whatever parses it).
 */
/** Where the product lives. The generated README credits it and says where to get it. */
export const AGENT_BLUEPRINT_URL = 'https://github.com/dimsour/agent-blueprint-engine'

export function generatedHeader(sourcePath: string): string {
  return `<!-- Generated by Agent Blueprint from ${sourcePath}. Edit the source, not this file. -->`
}

export const GENERATED_HEADER_RE =
  /^<!-- Generated by Agent Blueprint from .+\. Edit the source, not this file\. -->$/m

/** Prefixes a Markdown body with the header comment. */
export function withHeader(sourcePath: string, body: string): string {
  const trimmed = body.replace(/^\n+/, '')
  return trimmed.length === 0
    ? `${generatedHeader(sourcePath)}\n`
    : `${generatedHeader(sourcePath)}\n\n${trimmed}`
}
