import { HARNESS_IDS } from '@agent-blueprint/core'
import { parse as parseToml } from 'smol-toml'
import { describe, expect, it } from 'vitest'

import {
  ADAPTERS,
  adapterFor,
  compileBlueprint,
  CONCEPTS,
  GENERATED_HEADER_RE,
  listAdapters,
} from '../src/index'
import { loadFixture } from './helpers'

describe('registry', () => {
  it('has an adapter for every harness id', () => {
    expect(Object.keys(ADAPTERS).sort()).toEqual([...HARNESS_IDS].sort())
    for (const id of HARNESS_IDS) expect(adapterFor(id).id).toBe(id)
  })

  it('describes every concept with a non-empty explanation', () => {
    for (const adapter of listAdapters()) {
      expect(Object.keys(adapter.capabilities).sort()).toEqual([...CONCEPTS].sort())
      for (const concept of CONCEPTS) {
        const capability = adapter.capabilities[concept]
        expect(capability.explanation.length, `${adapter.id}/${concept}`).toBeGreaterThan(20)
        expect(['native', 'adapted', 'limited', 'unsupported']).toContain(capability.support)
      }
    }
  })

  it('accepts empty options and rejects unknown option types', () => {
    for (const adapter of listAdapters()) {
      expect(() => {
        adapter.parseOptions({})
      }).not.toThrow()
    }
    expect(() => {
      adapterFor('claude-code').parseOptions({ emitSettings: 'yes' })
    }).toThrow()
  })
})

describe('generated files', () => {
  it('are relative POSIX paths without traversal', async () => {
    const blueprint = await loadFixture()
    const { files } = compileBlueprint(blueprint, { targets: [...HARNESS_IDS] })
    expect(files.length).toBeGreaterThan(10)
    for (const file of files) {
      expect(file.path, file.path).not.toMatch(/^[/\\]|^[A-Za-z]:|\\/)
      expect(file.path.split('/'), file.path).not.toContain('..')
      expect(file.content.endsWith('\n'), file.path).toBe(true)
      expect(file.content.includes('\r'), file.path).toBe(false)
    }
  })

  it('put the generated-file header in Markdown only, after any frontmatter', async () => {
    const blueprint = await loadFixture()
    const { files } = compileBlueprint(blueprint, { targets: [...HARNESS_IDS] })
    for (const file of files) {
      if (file.format === 'markdown') {
        expect(GENERATED_HEADER_RE.test(file.content), `${file.path} has no header`).toBe(true)
        if (file.content.startsWith('---\n')) {
          const body = file.content.slice(file.content.indexOf('\n---\n') + 5)
          expect(body.trimStart().startsWith('<!-- Generated'), file.path).toBe(true)
        }
      } else {
        expect(file.content.includes('Generated by Agent Blueprint'), file.path).toBe(false)
      }
    }
  })

  it('contain no timestamps or absolute machine paths', async () => {
    const blueprint = await loadFixture()
    const { files } = compileBlueprint(blueprint, { targets: [...HARNESS_IDS] })
    for (const file of files) {
      expect(file.content, file.path).not.toMatch(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/)
      expect(file.content, file.path).not.toMatch(/[A-Z]:\\Users/)
    }
  })
})

describe('claude-code adapter', () => {
  it('emits the documented file set for the fixture', async () => {
    const blueprint = await loadFixture()
    const { files } = compileBlueprint(blueprint, { targets: ['claude-code'] })
    const paths = files.map((file) => file.path)

    expect(paths).toContain('CLAUDE.md')
    expect(paths).toContain('.claude/settings.json')
    expect(paths).toContain('.claude/rules/prefer-existing-framework.md')
    expect(paths).toContain('.claude/skills/xunit/SKILL.md')
    expect(paths).toContain('.claude/skills/xunit/references/xunit-patterns.md')
    expect(paths).toContain('.claude/skills/xunit/references/testing-patterns.md')
    expect(paths).toContain('.claude/skills/write-tests/SKILL.md')
    // A single agent is the primary agent, so it has no subagent file.
    expect(paths.filter((path) => path.startsWith('.claude/agents/'))).toEqual([])
    // testing-patterns is attached to skills, so it is not duplicated at the top level.
    expect(paths.filter((path) => path.startsWith('.claude/references/'))).toEqual([])
  })

  it('lowers permissions and hooks into settings.json', async () => {
    const blueprint = await loadFixture()
    const { files } = compileBlueprint(blueprint, { targets: ['claude-code'] })
    const settingsFile = files.find((file) => file.path === '.claude/settings.json')!
    const settings = JSON.parse(settingsFile.content) as {
      permissions: { allow: string[]; ask: string[]; deny: string[] }
      hooks: Record<string, { matcher?: string; hooks: { type: string; command?: string }[] }[]>
      autoMemoryEnabled: boolean
    }

    expect(settings.permissions.allow).toContain('Read')
    expect(settings.permissions.allow).toContain('Edit')
    expect(settings.permissions.allow).toContain('Bash(dotnet test *)')
    expect(settings.permissions.ask).toContain('Bash')
    expect(settings.permissions.ask).toContain('Bash(rm *)')
    expect(settings.permissions.deny).toContain('Bash(git push *)')
    expect(settings.permissions.deny).toContain('WebFetch')

    expect(settings.hooks.PostToolUse?.[0]?.matcher).toBe('Edit|Write')
    expect(settings.hooks.PostToolUse?.[0]?.hooks[0]?.command).toBe('dotnet test --no-restore')
    // The gate command and the Iron Law check both run when the session stops.
    const stop = settings.hooks.Stop ?? []
    expect(stop[0]?.hooks.map((handler) => handler.type)).toEqual(['command', 'prompt'])
    expect(stop[0]?.hooks[0]?.command).toBe('dotnet test')
    expect(settings.autoMemoryEnabled).toBe(true)
  })

  it('reports an error when a workflow and a skill share an id', async () => {
    const blueprint = structuredClone(await loadFixture())
    blueprint.workflows[0]!.id = 'xunit'
    const diagnostics = adapterFor('claude-code').validate(blueprint, { emitSettings: true })
    expect(diagnostics.map((diagnostic) => diagnostic.code)).toEqual(['BP-CLAUDE-001'])
    expect(diagnostics[0]?.severity).toBe('error')
  })
})

describe('codex adapter', () => {
  it('emits the portable set plus Codex-specific files', async () => {
    const blueprint = await loadFixture()
    const { files } = compileBlueprint(blueprint, { targets: ['codex'] })
    const paths = files.map((file) => file.path)

    expect(paths).toContain('AGENTS.md')
    expect(paths).toContain('.agents/skills/xunit/SKILL.md')
    expect(paths).toContain('.agents/skills/xunit/agents/openai.yaml')
    expect(paths).toContain('.agents/skills/write-tests/SKILL.md')
    expect(paths).toContain('.codex/config.toml')
    expect(paths).toContain('.codex/hooks.json')
    expect(paths.filter((path) => path.startsWith('.codex/agents/'))).toEqual([])
  })

  it('writes a config the TOML parser accepts', async () => {
    const blueprint = await loadFixture()
    const { files } = compileBlueprint(blueprint, { targets: ['codex'] })
    const config = parseToml(files.find((file) => file.path === '.codex/config.toml')!.content) as {
      approval_policy: string
      sandbox_mode: string
      features: Record<string, boolean>
      memories: Record<string, boolean>
      sandbox_workspace_write: { network_access: boolean }
    }

    expect(config.approval_policy).toBe('on-request')
    expect(config.sandbox_mode).toBe('workspace-write')
    expect(config.sandbox_workspace_write.network_access).toBe(false)
    expect(config.features).toEqual({ hooks: true, memories: true })
    expect(config.memories).toEqual({ generate_memories: true, use_memories: true })
  })

  it('keeps AGENTS.md inside the instruction budget', async () => {
    const blueprint = await loadFixture()
    const { files } = compileBlueprint(blueprint, { targets: ['codex'] })
    const agentsMd = files.find((file) => file.path === 'AGENTS.md')!
    expect(new TextEncoder().encode(agentsMd.content).length).toBeLessThan(30 * 1024)
    expect(
      adapterFor('codex').validate(blueprint, { instructionsMaxBytes: 30720, emitConfig: true }),
    ).toEqual([])
  })
})

describe('portable adapters', () => {
  it('produce the same AGENTS.md and skills as Codex so the files can be shared', async () => {
    const blueprint = await loadFixture()
    const codex = compileBlueprint(blueprint, { targets: ['codex'] })
    for (const target of ['opencode', 'pi'] as const) {
      const other = compileBlueprint(blueprint, { targets: [target] })
      for (const file of other.files) {
        if (!file.path.startsWith('.agents/') && file.path !== 'AGENTS.md') continue
        const twin = codex.files.find((candidate) => candidate.path === file.path)
        expect(twin, `${target} ${file.path}`).toBeDefined()
        expect(file.content, `${target} ${file.path}`).toBe(twin?.content)
      }
    }
  })

  it('report what they cannot represent', async () => {
    const blueprint = await loadFixture()
    const { issues } = compileBlueprint(blueprint, { targets: ['pi'] })
    const memory = issues.find((issue) => issue.concept === 'memory')
    expect(memory?.support).toBe('unsupported')
    expect(memory?.message).toContain('no persistent memory')
  })

  it('give Copilot its own skills directory and instructions pointer', async () => {
    const blueprint = await loadFixture()
    const paths = compileBlueprint(blueprint, { targets: ['copilot'] }).files.map(
      (file) => file.path,
    )
    expect(paths).toContain('.github/skills/xunit/SKILL.md')
    expect(paths).toContain('.github/copilot-instructions.md')
    expect(paths).toContain('AGENTS.md')
  })
})
