import { HARNESS_IDS } from '@agent-blueprint/core'
import { parse as parseToml } from 'smol-toml'
import { describe, expect, it } from 'vitest'

import {
  ADAPTERS,
  adapterFor,
  compileBlueprint,
  CONCEPTS,
  GENERATED_HEADER_RE,
  listAdapters,
} from '../src/index'
import { loadFixture, textOf } from './helpers'

describe('registry', () => {
  it('has an adapter for every harness id', () => {
    expect(Object.keys(ADAPTERS).sort()).toEqual([...HARNESS_IDS].sort())
    for (const id of HARNESS_IDS) expect(adapterFor(id).id).toBe(id)
  })

  it('describes every concept with a non-empty explanation', () => {
    for (const adapter of listAdapters()) {
      expect(Object.keys(adapter.capabilities).sort()).toEqual([...CONCEPTS].sort())
      for (const concept of CONCEPTS) {
        const capability = adapter.capabilities[concept]
        expect(capability.explanation.length, `${adapter.id}/${concept}`).toBeGreaterThan(20)
        expect(['native', 'adapted', 'limited', 'unsupported']).toContain(capability.support)
      }
    }
  })

  it('accepts empty options and rejects unknown option types', () => {
    for (const adapter of listAdapters()) {
      expect(() => {
        adapter.parseOptions({})
      }).not.toThrow()
    }
    expect(() => {
      adapterFor('claude-code').parseOptions({ emitSettings: 'yes' })
    }).toThrow()
  })
})

describe('generated files', () => {
  it('are relative POSIX paths without traversal', async () => {
    const blueprint = await loadFixture()
    const { files } = compileBlueprint(blueprint, { targets: [...HARNESS_IDS] })
    expect(files.length).toBeGreaterThan(10)
    for (const file of files) {
      expect(file.path, file.path).not.toMatch(/^[/\\]|^[A-Za-z]:|\\/)
      expect(file.path.split('/'), file.path).not.toContain('..')
      // A binary asset is copied byte for byte; a trailing newline would corrupt it.
      if (file.format === 'binary') continue
      expect(textOf(file).endsWith('\n'), file.path).toBe(true)
      expect(textOf(file).includes('\r'), file.path).toBe(false)
    }
  })

  it('put the generated-file header in Markdown only, after any frontmatter', async () => {
    const blueprint = await loadFixture()
    const { files } = compileBlueprint(blueprint, { targets: [...HARNESS_IDS] })
    for (const file of files) {
      if (file.format === 'markdown') {
        const content = textOf(file)
        expect(GENERATED_HEADER_RE.test(content), `${file.path} has no header`).toBe(true)
        if (content.startsWith('---\n')) {
          const body = content.slice(content.indexOf('\n---\n') + 5)
          expect(body.trimStart().startsWith('<!-- Generated'), file.path).toBe(true)
        }
      } else if (file.format !== 'binary') {
        expect(textOf(file).includes('Generated by Agent Blueprint'), file.path).toBe(false)
      }
    }
  })

  it('contain no timestamps or absolute machine paths', async () => {
    const blueprint = await loadFixture()
    const { files } = compileBlueprint(blueprint, { targets: [...HARNESS_IDS] })
    for (const file of files) {
      if (file.format === 'binary') continue
      expect(textOf(file), file.path).not.toMatch(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/)
      expect(textOf(file), file.path).not.toMatch(/[A-Z]:\\Users/)
    }
  })
})

/** The failure wrapper of P9-25 / P9-30 around a command, as the adapters emit it. */
const wrapped = (command: string, code: 2 | 1, note?: string) =>
  `out=$(${command} 2>&1) || { ${note ? `printf '%s\\n' '${note}' >&2; ` : ''}printf '%s\\n' "$out" >&2; exit ${code}; }; [ -z "$out" ] || printf '%s\\n' "$out"`

describe('claude-code adapter', () => {
  it('emits the documented file set for the fixture', async () => {
    const blueprint = await loadFixture()
    const { files } = compileBlueprint(blueprint, { targets: ['claude-code'] })
    const paths = files.map((file) => file.path)

    expect(paths).toContain('CLAUDE.md')
    expect(paths).toContain('.claude/settings.json')
    expect(paths).toContain('.claude/rules/prefer-existing-framework.md')
    expect(paths).toContain('.claude/skills/xunit/SKILL.md')
    expect(paths).toContain('.claude/skills/xunit/references/xunit-patterns.md')
    expect(paths).toContain('.claude/skills/xunit/references/testing-patterns.md')
    expect(paths).toContain('.claude/skills/write-tests/SKILL.md')
    // A single agent is the primary agent, so it has no subagent file.
    expect(paths.filter((path) => path.startsWith('.claude/agents/'))).toEqual([])
    // testing-patterns is attached to skills, so it is not duplicated at the top level.
    expect(paths.filter((path) => path.startsWith('.claude/references/'))).toEqual([])
  })

  it('lowers permissions and hooks into settings.json', async () => {
    const blueprint = await loadFixture()
    const { files } = compileBlueprint(blueprint, { targets: ['claude-code'] })
    const settingsFile = files.find((file) => file.path === '.claude/settings.json')!
    const settings = JSON.parse(textOf(settingsFile)) as {
      permissions: { allow: string[]; ask: string[]; deny: string[] }
      hooks: Record<
        string,
        { matcher?: string; hooks: { type: string; command?: string; if?: string }[] }[]
      >
      autoMemoryEnabled: boolean
    }

    expect(settings.permissions.allow).toContain('Read')
    expect(settings.permissions.allow).toContain('Edit')
    expect(settings.permissions.allow).toContain('Bash(dotnet test *)')
    expect(settings.permissions.ask).toContain('Bash')
    expect(settings.permissions.ask).toContain('Bash(rm *)')
    expect(settings.permissions.deny).toContain('Bash(git push *)')
    expect(settings.permissions.deny).toContain('WebFetch')

    expect(settings.hooks.PostToolUse?.[0]?.matcher).toBe('Edit|Write')
    // `return-to-agent`: the output reaches the model only through exit 2 and stderr, so the
    // command is wrapped to do exactly that when it fails, and to say nothing when it passes.
    expect(settings.hooks.PostToolUse?.[0]?.hooks[0]?.command).toBe(
      wrapped('dotnet test --no-restore', 2),
    )
    // The hook is for C# files, and Claude can filter the tool call by path itself.
    expect(settings.hooks.PostToolUse?.[0]?.hooks[0]?.if).toBe('Edit(**/*.cs)|Write(**/*.cs)')
    // The gate command and the Iron Law check both run when the session stops.
    const stop = settings.hooks.Stop ?? []
    expect(stop[0]?.hooks.map((handler) => handler.type)).toEqual(['command', 'prompt'])
    expect(stop[0]?.hooks[0]?.command).toBe(wrapped('dotnet test', 2))
    expect(settings.autoMemoryEnabled).toBe(true)
  })

  /**
   * A hook that only warns must not refuse anything: exit 1 reports and continues. A gate
   * that allows failure must not even report. And a file pattern on an event that is not
   * about a tool has nothing to filter, so it stays a note (P9-25).
   */
  it('makes a failure mean what the Blueprint says, and filters only what it can', async () => {
    const blueprint = structuredClone(await loadFixture())
    const hook = blueprint.hooks[0]!
    hook.onFailure = 'warn'
    blueprint.hooks.push({
      ...structuredClone(hook),
      id: 'scan-before-stop',
      name: 'Scan before stop',
      trigger: 'before-stop',
      onFailure: 'block',
      action: { type: 'secret-scan', command: 'scan-secrets', async: false },
    })
    blueprint.hooks.push({
      ...structuredClone(hook),
      id: 'shell-guard',
      name: 'Shell guard',
      trigger: 'before-tool',
      conditions: { toolKinds: ['shell'], filePatterns: ['**/*.cs'] },
      onFailure: 'block',
      action: { type: 'command', command: 'guard', async: false },
    })
    blueprint.gates[0]!.onFail = 'allow'
    blueprint.gates.push({
      ...structuredClone(blueprint.gates[0]!),
      id: 'approval',
      name: 'Approval',
      onFail: 'request-approval',
      criteria: [{ kind: 'command', command: 'check', description: 'Check.' }],
    })

    const { files, issues } = compileBlueprint(blueprint, { targets: ['claude-code'] })
    const settings = JSON.parse(textOf(files.find((f) => f.path === '.claude/settings.json'))) as {
      hooks: Record<
        string,
        { matcher?: string; hooks: { command?: string; if?: string; type: string }[] }[]
      >
    }

    expect(settings.hooks.PostToolUse?.[0]?.hooks[0]?.command).toBe(
      wrapped('dotnet test --no-restore', 1),
    )
    const stopCommands = (settings.hooks.Stop ?? []).flatMap((entry) =>
      entry.hooks.map((handler) => handler.command),
    )
    expect(stopCommands).toContain(wrapped('scan-secrets', 2))
    expect(stopCommands).toContain('dotnet test || true')
    expect(stopCommands).toContain(
      wrapped('check', 2, 'Approval failed. Ask the user before continuing.'),
    )
    // A Bash hook has no path to filter by: the pattern stays a note, and an issue says so.
    const guard = settings.hooks.PreToolUse?.find((entry) => entry.matcher === 'Bash')?.hooks[0]
    expect(guard?.if).toBeUndefined()
    expect(issues.some((i) => i.ref?.id === 'shell-guard' && i.concept === 'hooks')).toBe(true)
    // The C# hook is filtered natively, so it is not reported as a limitation any more.
    expect(issues.some((i) => i.ref?.id === hook.id && i.concept === 'hooks')).toBe(false)
  })

  it('reports an error when a workflow and a skill share an id', async () => {
    const blueprint = structuredClone(await loadFixture())
    blueprint.workflows[0]!.id = 'xunit'
    const diagnostics = adapterFor('claude-code').validate(blueprint, { emitSettings: true })
    expect(diagnostics.map((diagnostic) => diagnostic.code)).toEqual(['BP-CLAUDE-001'])
    expect(diagnostics[0]?.severity).toBe('error')
  })

  /**
   * A subagent's permissions used to be dropped: only the primary agent's became rules, and
   * a reviewer that must not write got a permission mode and nothing else (P9-26). A denial
   * turns a whole tool off when every operation behind it is denied; a denial that cannot
   * (pushing, while the shell stays) is written into the prompt instead. And an agent that
   * delegates keeps the Agent tool on its list, or the list would take delegation away.
   */
  it('gives a subagent its denials, and the Agent tool when it delegates', async () => {
    const blueprint = structuredClone(await loadFixture())
    const primary = blueprint.agents[0]!
    blueprint.agents.push({
      ...structuredClone(primary),
      id: 'reviewer',
      name: 'Reviewer',
      role: 'reviewer',
      toolIds: ['filesystem', 'dotnet-cli'],
      delegation: { canDelegateTo: [primary.id] },
      permissions: {
        operations: {
          'fs.read': 'allow',
          'fs.write': 'deny',
          'shell.readonly': 'allow',
          'git.push': 'deny',
          'net.any': 'deny',
        },
        patterns: [],
      },
    })

    const { files } = compileBlueprint(blueprint, { targets: ['claude-code', 'codex'] })
    const agent = textOf(files.find((file) => file.path === '.claude/agents/reviewer.md'))
    const frontmatter = agent.slice(0, agent.indexOf('\n---\n'))
    expect(frontmatter).toContain(
      'disallowedTools:\n  - Edit\n  - NotebookEdit\n  - WebFetch\n  - WebSearch\n  - Write',
    )
    // Write and Edit came from the filesystem tool; a tool that is turned off is not listed.
    expect(frontmatter).toContain(
      'tools:\n  - Bash\n  - Glob\n  - Grep\n  - Read\n  - Agent(testing-expert)',
    )
    // Bash survives because read-only commands are allowed, so the push ban is a sentence.
    expect(agent).toContain('## Not allowed\n- Never push to a remote.')
    expect(agent).not.toContain('Never create or edit files')

    const toml = textOf(files.find((file) => file.path === '.codex/agents/reviewer.toml'))
    expect(toml).toContain('sandbox_mode = "read-only"')
  })
})

/**
 * The four lifecycle triggers added in P9-29 and the background flag, across the three
 * adapters with JSON hooks. Each harness has a different subset of the events, and the test
 * pins what each one emits and what it reports instead.
 */
describe('lifecycle triggers and background hooks', () => {
  const hooksOf = async () => {
    const blueprint = structuredClone(await loadFixture())
    const base = blueprint.hooks[0]!
    const make = (id: string, trigger: typeof base.trigger, async = false) => ({
      ...structuredClone(base),
      id,
      name: id,
      trigger,
      conditions: { toolKinds: [], filePatterns: [] },
      onFailure: 'block' as const,
      action: { type: 'command' as const, command: `run-${id}`, async },
    })
    blueprint.hooks = [
      make('on-failure', 'after-tool-failure'),
      make('on-subagent', 'subagent-start'),
      make('before', 'before-compact'),
      make('after', 'after-compact'),
      make('log', 'after-tool', true),
    ]
    return compileBlueprint(blueprint, { targets: ['claude-code', 'codex', 'copilot'] })
  }

  it('lowers every one of them on Claude Code, and says which cannot refuse', async () => {
    const { files, issues } = await hooksOf()
    const settings = JSON.parse(textOf(files.find((f) => f.path === '.claude/settings.json'))) as {
      hooks: Record<string, { hooks: { command: string; async?: boolean }[] }[]>
    }
    expect(Object.keys(settings.hooks).sort()).toEqual([
      'PostCompact',
      'PostToolUse',
      'PostToolUseFailure',
      'PreCompact',
      'Stop',
      'SubagentStart',
    ])
    // A background hook runs as written: its result is discarded, so there is nothing to
    // wrap, and the flag is on the handler.
    expect(settings.hooks.PostToolUse?.[0]?.hooks[0]).toMatchObject({
      command: 'run-log',
      async: true,
    })
    // A blocking hook on an event that reports the past is told it cannot refuse.
    const claude = issues.filter(
      (issue) => issue.harnessId === 'claude-code' && issue.concept === 'hooks',
    )
    expect(claude.map((issue) => issue.ref?.id).sort()).toEqual([
      'after',
      'before',
      'on-failure',
      'on-subagent',
    ])
    expect(claude.every((issue) => issue.support === 'limited')).toBe(true)
  })

  it('drops the one event Codex lacks and reports it', async () => {
    const { files, issues } = await hooksOf()
    const hooks = JSON.parse(textOf(files.find((f) => f.path === '.codex/hooks.json'))) as {
      hooks: Record<string, { hooks: { command: string; async?: boolean }[] }[]>
    }
    expect(Object.keys(hooks.hooks).sort()).toEqual([
      'PostCompact',
      'PostToolUse',
      'PreCompact',
      'Stop',
      'SubagentStart',
    ])
    expect(hooks.hooks.PostToolUse?.[0]?.hooks[0]?.async).toBe(true)
    const dropped = issues.find(
      (issue) => issue.harnessId === 'codex' && issue.ref?.id === 'on-failure',
    )
    expect(dropped?.support).toBe('unsupported')
  })

  it('drops the one event Copilot lacks and runs background hooks in the foreground', async () => {
    const { files, issues } = await hooksOf()
    const hooks = JSON.parse(
      textOf(files.find((f) => f.path === '.github/hooks/blueprint.json')),
    ) as { hooks: Record<string, unknown[]> }
    expect(Object.keys(hooks.hooks).sort()).toEqual([
      'agentStop',
      'postToolUse',
      'postToolUseFailure',
      'preCompact',
      'subagentStart',
    ])
    const copilot = issues.filter((issue) => issue.harnessId === 'copilot')
    expect(copilot.find((issue) => issue.ref?.id === 'after')?.support).toBe('unsupported')
    expect(copilot.find((issue) => issue.ref?.id === 'log')?.support).toBe('limited')
  })
})

/**
 * A hook with a script ships the script and runs it (P9-30). Each harness keeps scripts in
 * its own place and runs them its own way; the script body is the same file everywhere.
 */
describe('hook scripts', () => {
  const withScript = async () => {
    const blueprint = structuredClone(await loadFixture())
    const hook = blueprint.hooks[0]!
    hook.action = {
      type: 'command',
      // The command is dead text once there is a script; the validator says so.
      command: 'ignored',
      script: 'set -e\ngrep -n "Thread.Sleep" "$1" && exit 2\nexit 0',
      async: false,
    }
    return compileBlueprint(blueprint, { targets: ['claude-code', 'codex', 'copilot'] })
  }

  it('writes the script once per harness with a shebang, and runs it from the hook', async () => {
    const { files } = await withScript()
    const byPath = (path: string) => textOf(files.find((file) => file.path === path))

    const script = '#!/usr/bin/env bash\nset -e\ngrep -n "Thread.Sleep" "$1" && exit 2\nexit 0\n'
    expect(byPath('.claude/hooks/run-tests-after-change.sh')).toBe(script)
    expect(byPath('.codex/hooks/run-tests-after-change.sh')).toBe(script)
    expect(byPath('.github/hooks/scripts/run-tests-after-change.sh')).toBe(script)

    const claude = JSON.parse(byPath('.claude/settings.json')) as {
      hooks: { PostToolUse: { hooks: { command: string }[] }[] }
    }
    expect(claude.hooks.PostToolUse[0]?.hooks[0]?.command).toContain(
      'bash "${CLAUDE_PROJECT_DIR}/.claude/hooks/run-tests-after-change.sh"',
    )
    expect(claude.hooks.PostToolUse[0]?.hooks[0]?.command).not.toContain('ignored')
    const codex = JSON.parse(byPath('.codex/hooks.json')) as {
      hooks: { PostToolUse: { hooks: { command: string }[] }[] }
    }
    expect(codex.hooks.PostToolUse[0]?.hooks[0]?.command).toContain(
      'bash .codex/hooks/run-tests-after-change.sh',
    )
    expect(byPath('.github/hooks/blueprint.json')).toContain(
      'bash .github/hooks/scripts/run-tests-after-change.sh',
    )
  })

  it('keeps a shebang the author wrote', async () => {
    const blueprint = structuredClone(await loadFixture())
    blueprint.hooks[0]!.action = { type: 'command', script: '#!/bin/sh\nexit 0\n', async: false }
    const { files } = compileBlueprint(blueprint, { targets: ['claude-code'] })
    expect(textOf(files.find((f) => f.path === '.claude/hooks/run-tests-after-change.sh'))).toBe(
      '#!/bin/sh\nexit 0\n',
    )
  })

  it('lets a passing hook answer on stdout', async () => {
    const blueprint = await loadFixture()
    const { files } = compileBlueprint(blueprint, { targets: ['claude-code'] })
    const settings = JSON.parse(textOf(files.find((f) => f.path === '.claude/settings.json'))) as {
      hooks: { PostToolUse: { hooks: { command: string }[] }[] }
    }
    // The wrapper only rewrites the failure path; on success the output is printed as it
    // was, so a script that prints a JSON decision or context is still heard.
    expect(settings.hooks.PostToolUse[0]?.hooks[0]?.command).toMatch(
      /; \[ -z "\$out" \] \|\| printf '%s\\n' "\$out"$/,
    )
  })
})

describe('codex adapter', () => {
  it('emits the portable set plus Codex-specific files', async () => {
    const blueprint = await loadFixture()
    const { files } = compileBlueprint(blueprint, { targets: ['codex'] })
    const paths = files.map((file) => file.path)

    expect(paths).toContain('AGENTS.md')
    expect(paths).toContain('.agents/skills/xunit/SKILL.md')
    expect(paths).toContain('.agents/skills/xunit/agents/openai.yaml')
    expect(paths).toContain('.agents/skills/write-tests/SKILL.md')
    expect(paths).toContain('.codex/config.toml')
    expect(paths).toContain('.codex/hooks.json')
    expect(paths.filter((path) => path.startsWith('.codex/agents/'))).toEqual([])
  })

  it('writes a config the TOML parser accepts', async () => {
    const blueprint = await loadFixture()
    const { files } = compileBlueprint(blueprint, { targets: ['codex'] })
    const config = parseToml(textOf(files.find((file) => file.path === '.codex/config.toml'))) as {
      approval_policy: string
      sandbox_mode: string
      features: Record<string, boolean>
      memories: Record<string, boolean>
      sandbox_workspace_write: { network_access: boolean }
    }

    expect(config.approval_policy).toBe('on-request')
    expect(config.sandbox_mode).toBe('workspace-write')
    expect(config.sandbox_workspace_write.network_access).toBe(false)
    expect(config.features).toEqual({ hooks: true, memories: true })
    expect(config.memories).toEqual({ generate_memories: true, use_memories: true })
  })

  it('keeps AGENTS.md inside the instruction budget', async () => {
    const blueprint = await loadFixture()
    const { files } = compileBlueprint(blueprint, { targets: ['codex'] })
    const agentsMd = files.find((file) => file.path === 'AGENTS.md')!
    expect(new TextEncoder().encode(textOf(agentsMd)).length).toBeLessThan(30 * 1024)
    expect(
      adapterFor('codex').validate(blueprint, { instructionsMaxBytes: 30720, emitConfig: true }),
    ).toEqual([])
  })
})

describe('portable adapters', () => {
  it('produce the same AGENTS.md and skills as Codex so the files can be shared', async () => {
    const blueprint = await loadFixture()
    const codex = compileBlueprint(blueprint, { targets: ['codex'] })
    for (const target of ['opencode', 'pi'] as const) {
      const other = compileBlueprint(blueprint, { targets: [target] })
      for (const file of other.files) {
        if (!file.path.startsWith('.agents/') && file.path !== 'AGENTS.md') continue
        const twin = codex.files.find((candidate) => candidate.path === file.path)
        expect(twin, `${target} ${file.path}`).toBeDefined()
        expect(file.content, `${target} ${file.path}`).toBe(twin?.content)
      }
    }
  })

  it('report what they cannot represent', async () => {
    const blueprint = await loadFixture()
    const { issues } = compileBlueprint(blueprint, { targets: ['pi'] })
    const memory = issues.find((issue) => issue.concept === 'memory')
    expect(memory?.support).toBe('unsupported')
    expect(memory?.message).toContain('no persistent memory')
  })

  it('share AGENTS.md with Copilot, which reads it too', async () => {
    const blueprint = await loadFixture()
    const codex = compileBlueprint(blueprint, { targets: ['codex'] })
    const copilot = compileBlueprint(blueprint, { targets: ['copilot'] })
    const agentsMd = (result: typeof codex) =>
      result.files.find((file) => file.path === 'AGENTS.md')
    expect(agentsMd(copilot)?.content).toBe(agentsMd(codex)?.content)
    expect(agentsMd(copilot)?.owner).toBe('shared')
  })
})
